In [3]:
import numpy as np
import math
np.set_printoptions(precision=3)

In [4]:
A = np.array([
    [12, -51, 4],
    [6, 167, -68],
    [-4, -24, -41]
])

In [5]:
ERROR = 0.000001

# Assignment 10

## QR Decomposition

In [6]:
def QR_decomposition_aux(A):
    rows, cols = A.shape
    Q = np.zeros((rows, rows))
    u = np.zeros((rows, rows))
    u[:, 0] = A[:, 0]
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])
    
    for i in range(1, rows):
        u[:, i] = A[:, i]
        for j in range(i):
            u[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j] #get each u vector
        Q[:, i] = u[:, i] / np.linalg.norm(u[:, i])
    R = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(i, cols):
            R[i, j] = A[:, j] @ Q[:, i]
    return Q, R
q, r = QR_decomposition_aux(A)

Adjust the signs of the columns in Q and the rows in R

In [7]:
def diag_sign(A):
    return np.diag(np.sign(np.diag(A)))
def adjust_sign(Q, R):
    D = diag_sign(Q)
    Q[:, :] = Q @ D
    R[:, :] = D @ R
    return Q, R

In [8]:
def QR_decomposition(A):
    return adjust_sign(*QR_decomposition_aux(A))

In [10]:
Q, R = QR_decomposition(A)

In [11]:
print(Q)
print(R)

[[ 0.857 -0.467  0.217]
 [ 0.429  0.88   0.203]
 [-0.286 -0.081  0.955]]
[[ 14.     34.714 -14.   ]
 [  0.    172.803 -58.39 ]
 [  0.      0.    -52.111]]


In [150]:
Q @ R

array([[ 12., -51.,   4.],
       [  6., 167., -68.],
       [ -4., -24., -41.]])

In [151]:
A

array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4, -24, -41]])