In [2]:
%%capture
%run ../Assignment03-LU/LU.ipynb

In [3]:
import numpy as np

In [4]:
A2 =  np.array([
  np.array([7, 9], dtype=float),
  np.array([9, 7], dtype=float),
])

In [5]:
x2 = np.array([
  np.array([-1], dtype=float),
  np.array([0.5], dtype=float),
])

In [6]:
A =  np.array([
  np.array([40, 3, 9, 7, 8], dtype=float),
  np.array([3, 23, 4, 7, 12], dtype=float),
  np.array([9, 4, 65, 16, 15], dtype=float),
  np.array([7, 7, 16, 37, 12], dtype=float),
  np.array([8, 12, 15, 12, 51], dtype=float),
])
A

array([[40.,  3.,  9.,  7.,  8.],
       [ 3., 23.,  4.,  7., 12.],
       [ 9.,  4., 65., 16., 15.],
       [ 7.,  7., 16., 37., 12.],
       [ 8., 12., 15., 12., 51.]])

In [7]:
x = np.array([
  np.array([1], dtype=float),
  np.array([1], dtype=float),
  np.array([1], dtype=float),
  np.array([1], dtype=float),
  np.array([1], dtype=float),
])
x

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [8]:
error = 0.0001

In [9]:
def PowerMethod(A, x, error):
    xc = x.copy()
    v = xc / np.linalg.norm(xc)
    lambdaN = 0
    while True:
        lambdai = lambdaN
        xc = np.array(A @ v).flatten()
        lambdaN = (v.T @ xc).flatten()[0]
        v = xc / np.linalg.norm(xc)
        test = np.abs((lambdaN - lambdai) / lambdaN)
        if (test < error):
            break
    return lambdaN, v
pr, xr = PowerMethod(A2,x2, error)
pr, xr

(15.999990344052728, array([-0.70704204, -0.70717152]))

In [10]:
def InvertedPowerMethod(A, x, error):
    xc = x.copy();
    lambdaN = 0
    v = xc / np.linalg.norm(xc)
    while True: 
        lambdai = lambdaN
        L, U, xc, perm = LU(A, xc)
        lambdaN = np.array(v.T @ xc).flatten()[0]
        v = xc / np.linalg.norm(xc)
        test = np.abs((lambdaN - lambdai) / lambdaN)
        if (test < error):
            break
    lambdaN = 1 / lambdaN
    return lambdaN, v
pi, xi = InvertedPowerMethod(A2, x2, error)
pi, xi

(7.777475296882046e-05,
 array([[-7.77747530e-05],
        [ 9.99999997e-01]]))

In [11]:
def PI(A, x, E):
    Ai = np.linalg.inv(A)
    lambdai, v = PowerMethod(Ai, x, E)
    lambdai = 1/lambdai
    return lambdai, v
PI(A2, x2, error)

(-2.000000953674367, array([-0.70716432,  0.70704923]))

In [12]:
def DislocatedPowerMethod(A, x, error, mu):
    I = np.eye(A.shape[0])
    A_ = A - (mu)*I
    
    lambdan, xn = InvertedPowerMethod(A_,x,error)
    lambdai = lambdan + mu
    xi = xn
    
    return lambdai, xi
mu = ((pr + pi)/2)+1
pd, xd = DislocatedPowerMethod(A2, x2, error, mu)
pd, xd

(9.00005628002834,
 array([[-2.22206255e-05],
        [-1.00000000e+00]]))