In [1]:
import numpy as np

In [2]:
%run "..\Assignment05-RREF\RREF.ipynb"

## Test Matrices

In [3]:
A = np.array([
  np.array([1, 1, 1], dtype=float),
  np.array([1, 0, 2], dtype=float),
])
A

array([[1., 1., 1.],
       [1., 0., 2.]])

In [4]:
A.T

array([[1., 1.],
       [1., 0.],
       [1., 2.]])

In [5]:
A2 = np.random.randint(0, 10, 9).reshape((3, 3))
A2

array([[5, 0, 1],
       [9, 7, 0],
       [6, 4, 2]])

# There are two implementations:

## First

In [6]:
def orthogonalize(A, n):
    b = A[:, n][:, np.newaxis]
    if n == 0:
        v = A[n]
        return np.array(b / np.linalg.norm(b))
    else:
        # get subspace with antecessors vectors to project b
        X = A[:, range(0, n)]
        # create NxN identity matrix
        I = np.eye(X.shape[0])
        M = I - X @ np.linalg.inv(X.T @ X) @ X.T
        e = M.dot(b)
        return e /np.linalg.norm(e)        

In [7]:
def q(A):
    length = np.min(A.shape)
    return np.concatenate([orthogonalize(A, i) for i in range(length)], axis=1)
Q2 = q(A2)
Q2

array([[ 0.41959068, -0.89569524, -0.14721987],
       [ 0.75526322,  0.43446367, -0.4907329 ],
       [ 0.50350881,  0.0947172 ,  0.85878258]])

In [8]:
R2 = Q2.T @ A2
R2

array([[ 1.19163753e+01,  7.30087782e+00,  1.42660831e+00],
       [-9.71445147e-16,  3.42011449e+00, -7.06260848e-01],
       [ 7.77156117e-15,  4.44089210e-15,  1.57034530e+00]])

In [9]:
# A = QR
Q2 @ R2

array([[5.00000000e+00, 5.00520640e-16, 1.00000000e+00],
       [9.00000000e+00, 7.00000000e+00, 5.39854102e-16],
       [6.00000000e+00, 4.00000000e+00, 2.00000000e+00]])

## Second

In [10]:
def grandSchimidt(A):
    Q = []
    a0 = A[:, 0]    
    Q.append(np.array(a0 / np.linalg.norm(a0)))
    n = np.min(A.shape)
    for b in range(1, n):
        new_col = old_col = np.array(A[:, b]).astype('float64')
        for a in range(b): 
            v = A[:, a]
            # A.T@b / A.T@A
            ratio = ((v.T@old_col)/(v.T@v))
            new_col -= ratio * v
        Q.append(np.array(new_col / np.linalg.norm(new_col)))
        
    return np.array(Q).T

Q = grandSchimidt(A.T)
Q

array([[ 0.57735027,  0.        ],
       [ 0.57735027, -0.70710678],
       [ 0.57735027,  0.70710678]])

In [11]:
R = Q.T.dot(A.T)

In [12]:
# A = QR
Q @ R

array([[1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 3.99346924e-16],
       [1.00000000e+00, 2.00000000e+00]])

In [13]:
A.T

array([[1., 1.],
       [1., 0.],
       [1., 2.]])

# Using RREF to get an base.

In [14]:
base = RREF(A)
base

array([[ 1.,  0.,  2.],
       [ 0.,  1., -1.]])

In [15]:
grandSchimidt(base)

array([[1., 0.],
       [0., 1.]])