In [1]:
import numpy as np

In [2]:
matrix = np.array([
  np.array([20, 7, 9], dtype=float),
  np.array([7, 30, 8], dtype=float),
  np.array([9, 8, 30], dtype=float),
])

In [3]:
matrix2 = np.array([
  np.array([5, 8, 9], dtype=float),
  np.array([4, 3, 2], dtype=float),
  np.array([6, 7, 5], dtype=float),
])

In [4]:
b = np.array([
  np.array([16], dtype=float),
  np.array([38], dtype=float),
  np.array([38], dtype=float),
])

In [5]:
matrix2

array([[5., 8., 9.],
       [4., 3., 2.],
       [6., 7., 5.]])

In [6]:
# Fint the biggest value (in module) in a matrix
# Parameters:
#    M - Matrix
# Return
#   - The row and column index of the biggest value in the matrix
def find_biggest_value_id(M):
    max_number = 0
    row_idx = 0
    col_idx = 0
    for idr, row in enumerate(M):
        n = row.max() if row.max() > abs(row.min()) else abs(row.min())
        col_arg = row.argmax() if row.max() > abs(row.min()) else row.argmin()
        if(n > max_number):
            max_number = n
            row_idx = idr
            col_idx = col_arg
                
    return row_idx, col_idx
# find_biggest_value_id(matrix2)

In [7]:
# Fint the biggest value (in module) in a specific column in a matrix
# Parameters:
#    M - Matrix
#    col_idx - Column index to operate with
# Return
#   - The row index of the biggest value in that passed column
def find_biggest_value_id_by_column(M, col_idx):
    column = M.T[col_idx]
    if (column.max() > abs(column.min())):
        return column.argmax()
    else:
        return column.argmin()
        

In [8]:
# Swap Lines in matrix
def swap_lines(M, line1, line2):
    M_copy = M.copy()
    M_copy[[line1, line2]] = M_copy[[line1, line2]]
    return M_copy

In [9]:
# Swap columns in a matrix and result
def swap_columns(M, b, col1, col2):
    M_copy = M.copy()
    b_ = b.copy()    
    M_copy[:, [col1, col2]] = M_copy[:, [col2, col1]]
    b_[[col1, col2]] = b_[[col2, col1]]
    return M_copy, b_
# swap_columns(matrix, b, 0, 1)

In [26]:
def elimination_with_partial_pivot(Matrix, b):
    M = Matrix.copy()
    b_ = b.copy()
    lines_size = len(M)
    col_size = M[0].size
    
    for c in range(col_size-1): # columns
        for l in range(c+1, lines_size): # lines
            if (M[l][c] < 0.0001):
                idx_biggest_line = find_biggest_value_id_by_column(M, c)
                if (idx_biggest_line != l):
                    M = swap_lines(M, idx_biggest_line, l)

            alfa = - M[l][c] / M[c][c]         
            M[l] += alfa*M[c]
            b_[l][0] += alfa*b_[c][0]
        
    return M, b_
M, b_ = elimination_with_partial_pivot(matrix, b)

print(M)
print(b_)

[[20.          7.          9.        ]
 [ 0.         27.55        4.85      ]
 [ 0.          0.         25.09618875]]
[[16.        ]
 [32.4       ]
 [25.09618875]]


In [33]:
def elimination_with_total_pivot(Matrix, b):
    M = Matrix.copy()
    b_ = b.copy()
    lines_size = len(M)
    col_size = M[0].size
    
    for c in range(col_size-1): # columns
        idx_biggest_line, idx_biggest_col = find_biggest_value_id(M)                 
        for l in range(c+1, lines_size): # lines
            if (M[l][c] < 0.0001):
                if (idx_biggest_col != c):
                    M, b_ = swap_columns(M, b_, idx_biggest_col, c)
                if (idx_biggest_line != l):
                    M = swap_lines(M, idx_biggest_line, l) 
            alfa = - M[l][c] / M[c][c]         
            M[l] += alfa*M[c]
            b_[l][0] += alfa*b_[c][0]
        
    return M, b_
M, b_ = elimination_with_total_pivot(matrix, b)

print(M)
print(b_)

[[20.          7.          9.        ]
 [ 0.         27.55        4.85      ]
 [ 0.          0.         25.09618875]]
[[16.        ]
 [32.4       ]
 [25.09618875]]


In [34]:
def back_substitution(M, b):
    M_ = M.copy()
    b_ = b.copy()
    b_size = b.size
    lines_size = len(M)
    col_size = M[0].size
    x = np.zeros((b_size, 1))
    
    x[b_size-1][0] =  b[b_size-1][0] / M[lines_size-1][lines_size-1]
    for i in range(lines_size-2, -1, -1):
        values_sum = 0
        for j in range(i+1, lines_size):
            values_sum += M[i][j] * x[j][0]
        x[i][0] = (b[i][0] - values_sum) / M[i][i]
    return x
back_substitution(M, b_)

array([[0.],
       [1.],
       [1.]])