In [1]:
import numpy as np

In [2]:
A = np.array([
  [ 4.0,  1.0, -2.0,  2.0],
  [ 1.0,  2.0,  0.0,  1.0],
  [ -2.0,  0.0, 3.0, -2.0],
  [ 2.0,  1.0, -2.0, -1.0]
])

In [3]:
def MountHouseHolder(A, c):
    rows, cols = A.shape
    v = np.zeros((rows,1))
    vLine = np.zeros((rows,1))
    
    v[c+1:rows, 0] = A[c+1:rows, c]
    
    lenghtV = np.linalg.norm(v)
    if(v[c+1,0] > 0):
        lenghtV = -1*lenghtV;
    
    vLine[c+1, 0] = lenghtV
    N = v - vLine
    n = N / np.linalg.norm(N)
    I = np.eye(rows)
    H = I - (2 * (n @ np.conj(n).T))
    
    return H
MountHouseHolder(A,0)

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.33333333,  0.66666667, -0.66666667],
       [ 0.        ,  0.66666667,  0.66666667,  0.33333333],
       [ 0.        , -0.66666667,  0.33333333,  0.66666667]])

In [4]:
def HouseHolder(A, show_iterations=True):
    cols = A.shape[1]
    Aline = A.copy()
    Hc = np.identity(cols)
    for c in range(cols-2):
        H = MountHouseHolder(Aline, c)
        Aline = H @ Aline @ H
        Hc = Hc @ H
        if (show_iterations):
            print("\n Iteration {} \n".format(c))
            print("HouseHolder Matrix {} : \n".format(c), np.matrix(H))
            print("Similar Tranformation Modified Matrix {} : \n".format(c), np.matrix(Aline))
            print("Cumalative HouseHolder Matrix {} : \n".format(c), np.matrix(Hc))
        
    return Aline, Hc
Aq, Ac = HouseHolder(A, True)


 Iteration 0 

HouseHolder Matrix 0 : 
 [[ 1.          0.          0.          0.        ]
 [ 0.         -0.33333333  0.66666667 -0.66666667]
 [ 0.          0.66666667  0.66666667  0.33333333]
 [ 0.         -0.66666667  0.33333333  0.66666667]]
Similar Tranformation Modified Matrix 0 : 
 [[ 4.00000000e+00 -3.00000000e+00  6.66133815e-16 -6.66133815e-16]
 [-3.00000000e+00  3.33333333e+00  1.00000000e+00  1.33333333e+00]
 [ 6.66133815e-16  1.00000000e+00  1.66666667e+00 -1.33333333e+00]
 [-6.66133815e-16  1.33333333e+00 -1.33333333e+00 -1.00000000e+00]]
Cumalative HouseHolder Matrix 0 : 
 [[ 1.          0.          0.          0.        ]
 [ 0.         -0.33333333  0.66666667 -0.66666667]
 [ 0.          0.66666667  0.66666667  0.33333333]
 [ 0.         -0.66666667  0.33333333  0.66666667]]

 Iteration 1 

HouseHolder Matrix 1 : 
 [[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   0.  -0.6 -0.8]
 [ 0.   0.  -0.8  0.6]]
Similar Tranformation Modified Matrix 1 : 
 [[ 4.00000000e+00 -3.0

In [5]:
print("\n Output Matrix: \n", np.matrix(Aq))
print('---------------------------------------------------------------------')
print("Cumalative HouseHolder Matrix: \n", np.matrix(Ac))


 Output Matrix: 
 [[ 4.00000000e+00 -3.00000000e+00  1.33226763e-16 -9.32587341e-16]
 [-3.00000000e+00  3.33333333e+00 -1.66666667e+00  8.88178420e-17]
 [ 1.33226763e-16 -1.66666667e+00 -1.32000000e+00  9.06666667e-01]
 [-9.32587341e-16 -4.44089210e-17  9.06666667e-01  1.98666667e+00]]
---------------------------------------------------------------------
Cumalative HouseHolder Matrix: 
 [[ 1.          0.          0.          0.        ]
 [ 0.         -0.33333333  0.13333333 -0.93333333]
 [ 0.          0.66666667 -0.66666667 -0.33333333]
 [ 0.         -0.66666667 -0.73333333  0.13333333]]
