In [29]:
import numpy as np
import math

In [30]:
A = np.array([
    [12, -51, 4],
    [6, 167, -68],
    [-4, -24, -41]
])

In [31]:
ERROR = 0.000001

In [68]:
# Build the QR's Identity Matrix (Pij)
def buildPijMatrix(A, i, j):
    rows, cols = A.shape
    Pij = np.identity(rows)
    t_aux = np.arctan(A[i,j] / A[j,j])
    teta = (np.pi/4) if (np.abs(A[j,j]) < ERROR) else t_aux
    Pij[i,i] = np.cos(teta)
    Pij[j,j] = np.cos(teta)
    Pij[i,j] = - np.sin(teta)
    Pij[j,i] = np.sin(teta)
    
    return Pij

In [73]:
def QR_Decomposition(A):
    H = A.copy()
    rows, cols = H.shape
    Qt = np.identity(rows)
    for j in range(cols-1):
        for i in range(j+1, rows):
            Pt = buildPijMatrix(A, i, j)
            H = Pt@H
            Qt = Pt@Qt
    return Qt.T, H
Q, R = decomposition(A)
print(Q)
print(R)

[[ 0.84852814 -0.48290039  0.21634974]
 [ 0.42426407  0.86521406  0.26721644]
 [-0.31622777 -0.13495125  0.93903576]]
[[ 1.39928331e+01  3.51666309e+01 -1.24905057e+01]
 [-6.37153359e-02  1.72357498e+02 -5.52331566e+01]
 [ 4.43352546e-01  1.10544506e+01 -5.58057853e+01]]


In [43]:
def calc_error(A):
    soma = 0
    for i in range(1, A.shape[0]):
        for j in range(1, A.shape[1]):
            if(i!=j):
                soma += A[i,j]**2
    return math.sqrt(soma)

In [66]:
def QR(A, e, H):
    M = A.copy()
    rows, cols = M.shape
    Q = np.zeros((rows, 1))
    R = np.zeros((rows, 1))
    
    P = H
    MAX_INTERATION = 2000
    i = 0
    error = calc_error(M)
    while(error > e and i < MAX_INTERATION):
        Q, R = QR_Decomposition(M)
        M = R@Q
        P = P@Q
        error = calc_error(M)
        i += 1
    return M, P
M, P = QR(Qt, ERROR, H)

In [48]:
M

array([[ 0.9904607 , -0.00323377,  0.13775755],
       [-0.00830485,  0.99650634,  0.08310325],
       [-0.13754501, -0.08345456,  0.98697351]])

In [49]:
P

array([[  6.09537076, -20.19335429, -22.90617897],
       [-83.60464932,  31.08052898, 161.9940262 ],
       [ 28.31859139, -38.3236034 ,  12.03908114]])