# RREF - Reducer Row Echelon Form
A matrix is in reducer row echelon form (also called row canonical form) if it satisfies the following coditions:
- It is in Row Echelon Form
- The leading entry in each nonzero row is a 1 (called leading 1)
- Each column containing a leading 1 has zeros in all its other entries

OBS: A matrix is in Row Echelon Form if it has the shape resulting from a Gaussian elimination.

In [1]:
import numpy as np
%run "../utils.ipynb"

In [2]:
echelon_M = np.array([
  np.array([1, 2, 2, 2], dtype=float),
  np.array([2, 4, 6, 8], dtype=float),
  np.array([3, 6, 8, 10], dtype=float),
])

In [3]:
M = echelon_M
M

array([[ 1.,  2.,  2.,  2.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  8., 10.]])

In [4]:
# Row Reduced Echelon Form
def RowEchelonForm(Matrix):
    M = Matrix.copy()
    n, m = M.shape
    if n == 0 or m == 0:
        return M
    # Determine the leftmost non-zero column.
    for i in range(len(M)):
        if M[i,0] != 0:
            break
    else:
        B = RowEchelonForm(M[:, 1:])
        return np.hstack([M[:,:1], B])
    # switch rows if non-zero element is not in first row
    if (i > 0):
        M = swap_lines(M, i, 0)
    # Use elementary row operations to put a 1 in the topmost position
    M[0] = M[0] / M[0,0]
    # Use elementary row operations to put zeros (strictly) below the pivot position.
    M[1:] -= M[0] * M[1:, 0:1]
    # Apply steps to submatrix
    B = RowEchelonForm(M[1:, 1:])
    # Add first row and first (zero) column and return
    return np.vstack([M[:1], np.hstack([M[1:,:1], B])])
RowEchelonForm(echelon_M)

array([[1., 2., 2., 2.],
       [0., 0., 1., 2.],
       [0., 0., 0., 0.]])

In [5]:
def reduce(M_echelon):
    A = M_echelon.copy()
    n, m = M_echelon.shape
    # Determine all the leading ones
    pivot_positions = []
    if m > n:
        iterNumber = m-1
    elif n > m:
        iterNumber = n-1
    else:
        iterNumber = m
    for c in range(iterNumber):
        if c< m and c < n and A[c][c] == 1:
            pivot_positions.append([c,c])
        else:
            for c_ in range(c+1, m-1):
                if c < n and c_ < m and A[c][c_] == 1:
                    pivot_positions.append([c, c_])
                    break
            continue
    for pivot_p in list(reversed(pivot_positions)):
        r, c = pivot_p
        for l in range(r-1, -1, -1):
            alfa = - A[l][c] / A[r][c]
            A[l] += alfa*A[r]
    return A, pivot_positions
# reduce(M)

In [6]:
# Row Reduced Echelon Form
def RREF(Matrix):
    M = RowEchelonForm(Matrix)
    return reduce(M)
M_RREF, pivot_positions = RREF(echelon_M)

print(M_RREF)
print(pivot_positions)

[[ 1.  2.  0. -2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]
[[0, 0], [1, 2]]


In [7]:
# 2- Receives a matrix in RREF and return its rank
def getRank(M_RREF):
    rank = 0
    M_lenght = M_RREF.shape[1]
    for idx, line in enumerate(M_RREF):
        if (idx < M_lenght):
            if(line[idx] > 0):
                rank += 1
    return rank
getRank(M_RREF)

1

In [8]:
# 3 Receives a matrix in RREF and return the dimension of the null space
def getNullSpaceDim(M_RREF):
    n = M_lenght = M_RREF.shape[1]
    rank = getRank(M_RREF)
    return n - rank
getNullSpaceDim(M_RREF)

3

In [9]:
teste = np.array([[ 1.,  3.,  3., -7.,  5.,  1.,  0.,  0.,  0.],
       [ 2.,  6.,  5., -8.,  1.,  0.,  1.,  0.,  0.],
       [ 3.,  9.,  5., -3., -2.,  0.,  0.,  1.,  0.],
       [ 4., 12.,  5.,  2., -5.,  0.,  0.,  0.,  1.]])
teste

array([[ 1.,  3.,  3., -7.,  5.,  1.,  0.,  0.,  0.],
       [ 2.,  6.,  5., -8.,  1.,  0.,  1.,  0.,  0.],
       [ 3.,  9.,  5., -3., -2.,  0.,  0.,  1.,  0.],
       [ 4., 12.,  5.,  2., -5.,  0.,  0.,  0.,  1.]])

In [10]:
matriz, pivos = RREF(teste)
print(matriz)
print(pivos)

[[  1.           3.           0.           0.          12.83333333
    4.16666667   0.          -6.83333333   4.33333333]
 [  0.           0.           1.           0.         -10.
   -3.           0.           5.          -3.        ]
 [  0.           0.           0.           1.          -3.16666667
   -0.83333333   0.           1.16666667  -0.66666667]
 [  0.           0.           0.           0.           0.
    0.           1.          -2.           1.        ]]
[[0, 0], [1, 2], [2, 3], [3, 6]]
