In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 0, -1],
    [-2, 1, 4],
])

# SVD - Singular Value Decomposition
SVD has a wide array of applications. These include dimensionality reduction, image compression, and denoising data. In essence, SVD states that a matrix can be represented as the product of three other matrices. In mathematical terms, SVD can be written as follows:
$Anxp = Unxn Snxp V^t pxp $

In [3]:
A[::-1]

array([[-2,  1,  4],
       [ 1,  0, -1]])

In [5]:
def SVD(A):
    # U is the eigenvectors of the Matrix (A @ A^t)
    U = A @ A.T
    _, U = np.linalg.eig(U)
    # V is the eigenvectors of the Matrix (A^t @ A)
    V = A.T @ A
    values, V = np.linalg.eig(V)
    V = V[::-1]
    S = np.zeros((A.shape))

    np.fill_diagonal(S, np.sqrt(values[::-1]))
    return U, V, S
    
U, V, S = SVD(A)

In [31]:
print(U)
print(V)
print(S)

[[ 0.817 -0.576  0.     0.   ]
 [ 0.576  0.817  0.     0.   ]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]
[[ 0.405 -0.915]
 [-0.915 -0.405]]
[[5.465 0.   ]
 [0.    0.366]
 [0.    0.   ]
 [0.    0.   ]]


In [32]:
U.shape

(4, 4)

In [33]:
S.shape

(4, 2)

In [34]:
V.T.shape

(2, 2)

In [35]:
U @ S @ V.T

array([[ 2., -4.],
       [ 1., -3.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [6]:
%%capture
%run "..\Assignment06_Gram_Schimidt\Gram_Schimidt.ipynb"

In [7]:
%%capture
%run "..\Assignment11-QR_EigenMethod\QR_EigenMethod.ipynb"

In [8]:
A = np.array([
    [1, 0, -1],
    [-2, 1, 4],
])

In [13]:
def SVD_decomposition(A, e=1e-5):
    rows, cols = A.shape
    eigenvaluesCount = min(rows, cols)
    firstZero = -1
    
    # rows > cols: Ut * A = S * Vt
    if (rows > cols):    
        # U is the eigenvectors of the Matrix (A @ A^t)
        U = A @ A.T
        # print(U)
        # eigenvalues, U = np.linalg.eig(U)        
        eigenvalues, U = eigenQR_general(U, np.eye(min(U.shape)))
        V = (U.T @ A)[0:cols, :].T
        S = np.zeros(A.shape)
        for i in range(eigenvaluesCount):
            if (abs(eigenvalues[i]) < e):
                S[i, i] = 0.0
                if (firstZero < 0):
                    firstZero = i
            else:
                S[i, i] = np.sqrt(eigenvalues[i])
                V[:, i] = V[:, i] / S[i, i]
        if (firstZero >= 0):
            V = grandSchimidt(V[:, 0:firstZero])
    # cols > rows: A * V = U * S
    else:
        # V is the eigenvectors of the Matrix (A^t @ A)
        V = A.T @ A
        # print(V)
        # eigenvalues, V = np.linalg.eig(V)
        eigenvalues, V = eigenQR_general(V,  np.eye(min(V.shape)))
        U = (A @ V)[:, 0:rows]
        S = np.zeros(A.shape)        
        for i in range(eigenvaluesCount):
            if (abs(eigenvalues[i]) < e):
                S[i, i] = 0.0
                if (firstZero < 0):
                    firstZero = i
            else:
                S[i, i] = np.sqrt(eigenvalues[i])
                U[:, i] = U[:, i] / S[i, i]
        if (firstZero >= 0):
            U = grandSchimidt(U[:, 0>firstZero])        
    return U, S, V
U, S, V = SVD_decomposition(A)
print("U: {}".format(U))
print("S: {}".format(S))
print("V: {}".format(V))

U: [[ 0.278+0.j  0.961+0.j]
 [-0.961+0.j  0.278+0.j]]
S: [[4.768 0.    0.   ]
 [0.    0.514 0.   ]]
V: [[ 0.461+0.j  0.788+0.j  0.   +0.j]
 [-0.201+0.j  0.541+0.j  0.   +0.j]
 [-0.864+0.j  0.294+0.j  0.   +0.j]]


In [10]:
U @ S @ V.T

array([[ 1.000e+00+0.j,  1.388e-15+0.j, -1.000e+00+0.j],
       [-2.000e+00+0.j,  1.000e+00+0.j,  4.000e+00+0.j]])

In [11]:
A

array([[ 1,  0, -1],
       [-2,  1,  4]])

In [42]:
M = np.array([[1, 0, -1], [-2, 1, 4]])

In [43]:
SVD_decomposition(M)

(array([[ 0.278+0.j,  0.961+0.j],
        [-0.961+0.j,  0.278+0.j]]),
 array([[4.768, 0.   , 0.   ],
        [0.   , 0.514, 0.   ]]),
 array([[ 0.461+0.j,  0.788+0.j,  0.   +0.j],
        [-0.201+0.j,  0.541+0.j,  0.   +0.j],
        [-0.864+0.j,  0.294+0.j,  0.   +0.j]]))