In [1]:
import numpy as np

In [10]:
A = np.array([
    [2, 4],
    [1, 3],
    [0, 0],
    [0, 0],
])

# SVD - Singular Value Decomposition
SVD has a wide array of applications. These include dimensionality reduction, image compression, and denoising data. In essence, SVD states that a matrix can be represented as the product of three other matrices. In mathematical terms, SVD can be written as follows:
$Anxp = Unxn Snxp V^t pxp $

In [3]:
A[::-1]

array([[0, 0],
       [0, 0],
       [1, 3],
       [2, 4]])

In [34]:
def SVD(A):
    # U is the eigenvectors of the Matrix (A @ A^t)
    U = A @ A.T
    _, U = np.linalg.eig(U)
    # V is the eigenvectors of the Matrix (A^t @ A)
    V = A.T @ A
    values, V = np.linalg.eig(V)
    V = V[::-1]
    S = np.zeros((A.shape))

    np.fill_diagonal(S, np.sqrt(values[::-1]))
    return U, V, S
    
U, V, S = SVD(A)

In [35]:
print(U)
print(V)
print(S)

[[ 0.817 -0.576  0.     0.   ]
 [ 0.576  0.817  0.     0.   ]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]
[[ 0.405 -0.915]
 [-0.915 -0.405]]
[[5.465 0.   ]
 [0.    0.366]
 [0.    0.   ]
 [0.    0.   ]]


In [99]:
U.shape

(4, 4)

In [100]:
S.shape

(4, 2)

In [101]:
V.T.shape

(2, 2)

In [102]:
U @ S @ V.T

array([[ 2., -4.],
       [ 1., -3.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [25]:
%run "..\Assignment06_Gram_Schimidt\Gram_Schimidt.ipynb"

[[ 1.  2.  0. -2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]
[[0, 0], [1, 2]]


In [30]:
%run "..\Assignment11-QR_EigenMethod\QR_EigenMethod.ipynb"

[[ 0.857 -0.467  0.217]
 [ 0.429  0.88   0.203]
 [-0.286 -0.081  0.955]]
[[ 14.     34.714 -14.   ]
 [  0.    172.803 -58.39 ]
 [  0.      0.    -52.111]]
16 Iterations
eigenvalues:
 [172.317 -49.19   14.873]
eigenvectors matrix:
 [[ 1.000e+00  7.143e-09 -1.512e-15]
 [-7.143e-09  1.000e+00 -2.795e-07]
 [-4.442e-17  2.795e-07  1.000e+00]]

 Iteration 0 

HouseHolder Matrix 0 : 
 [[ 1.     0.     0.     0.   ]
 [ 0.    -0.333  0.667 -0.667]
 [ 0.     0.667  0.667  0.333]
 [ 0.    -0.667  0.333  0.667]]
Similar Tranformation Modified Matrix 0 : 
 [[ 4.000e+00 -3.000e+00  6.661e-16 -6.661e-16]
 [-3.000e+00  3.333e+00  1.000e+00  1.333e+00]
 [ 6.661e-16  1.000e+00  1.667e+00 -1.333e+00]
 [-6.661e-16  1.333e+00 -1.333e+00 -1.000e+00]]
Cumalative HouseHolder Matrix 0 : 
 [[ 1.     0.     0.     0.   ]
 [ 0.    -0.333  0.667 -0.667]
 [ 0.     0.667  0.667  0.333]
 [ 0.    -0.667  0.333  0.667]]

 Iteration 1 

HouseHolder Matrix 1 : 
 [[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   0.  -

In [31]:
A = np.array([
    [2, 4],
    [1, 3],
    [0, 0],
    [0, 0],
])

In [42]:
def SVD_decomposition(A, e=1e-5):
    rows, cols = A.shape
    eigenvaluesCount = min(rows, cols)
    firstZero = -1
    
    # rows > cols: Ut * A = S * Vt
    if (rows > cols):    
        # U is the eigenvectors of the Matrix (A @ A^t)
        U = A @ A.T
        eigenvalues, U = np.linalg.eig(U)
        V = (U.T @ A)[0:cols, :].T
        S = np.zeros(A.shape)
        for i in range(eigenvaluesCount):
            if (abs(eigenvalues[i]) < e):
                S[i, i] = 0.0
                if (firstZero < 0):
                    firstZero = i
            else:
                S[i, i] = np.sqrt(eigenvalues[i])
                V[:, i] = V[:, i] / S[i, i]
        if (firstZero >= 0):
            V = grandSchimidt(V[:, 0:firstZero])
    # cols > rows: A * V = U * S
    else:
        # V is the eigenvectors of the Matrix (A^t @ A)
        V = A.T @ A
        eigenvalues, V = np.linalg.eig(V)
        U = (A @ V)[:, 0:rows]
        S = np.zeros(A.shape)        
        for i in range(eigenvaluesCount):
            if (abs(eigenvalues[i]) < e):
                S[i, i] = 0.0
                if (firstZero < 0):
                    firstZero = i
            else:
                S[i, i] = np.sqrt(eigenvalues[i])
                U[:, i] = U[:, i] / S[i, i]
        if (firstZero >= 0):
            U = grandSchimidt(U[:, 0>firstZero])        
    return U, np.diagonal(S), V
SVD_decomposition(A)

(array([[ 0.817, -0.576,  0.   ,  0.   ],
        [ 0.576,  0.817,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  1.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  1.   ]]),
 array([5.465, 0.366]),
 array([[ 0.405, -0.915],
        [ 0.915,  0.405]]))