# Gram-Schimidt
The Gram-Schimidt is a method to ortonormalize a set of vectors.
It receives a finite set of linear independent vectors and returns a set ortonormal which generates the same inicial subspace S.

In [1]:
import numpy as np

In [2]:
from sympy import *

In [3]:
%run "..\Assignment05-RREF\RREF.ipynb"

[[ 1.  2.  0. -2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]
[[0, 0], [1, 2]]
[[  1.           3.           0.           0.          12.83333333
    4.16666667   0.          -6.83333333   4.33333333]
 [  0.           0.           1.           0.         -10.
   -3.           0.           5.          -3.        ]
 [  0.           0.           0.           1.          -3.16666667
   -0.83333333   0.           1.16666667  -0.66666667]
 [  0.           0.           0.           0.           0.
    0.           1.          -2.           1.        ]]
[[0, 0], [1, 2], [2, 3], [3, 6]]


In [4]:
def orthogonalize(A, n):
    b = A[:, n][:, np.newaxis]
    if n == 0:
        v = A[n]
        return np.array(b / np.linalg.norm(b))
    else:
        # get subspace with antecessors vectors to project b
        X = A[:, range(0, n)]
        # create NxN identity matrix
        I = np.eye(X.shape[0])
        M = I - X @ np.linalg.inv(X.T @ X) @ X.T
        e = M.dot(b)
        return e /np.linalg.norm(e)   

In [5]:
def gramSchimidt(A):
    length = np.min(A.shape)
    return np.concatenate([orthogonalize(A, i) for i in range(length)], axis=1)

# Using RREF to get an base.

In [6]:
M = Matrix([
    [1, 3, 3, -7, 5],
    [2, 6, 5, -8, 1],
    [3, 9, 5, -3, -2],
    [4, 12, 5, 2, -5],
])

In [7]:
#A'
Mextended = Matrix(np.concatenate((M, np.identity(M.shape[0])), axis=1))
Mextended

Matrix([
[1,  3, 3, -7,  5, 1.0,   0,   0,   0],
[2,  6, 5, -8,  1,   0, 1.0,   0,   0],
[3,  9, 5, -3, -2,   0,   0, 1.0,   0],
[4, 12, 5,  2, -5,   0,   0,   0, 1.0]])

In [8]:
Mextended = np.array(Mextended).astype(np.float64) # convert to numpy
Mextended

array([[ 1.,  3.,  3., -7.,  5.,  1.,  0.,  0.,  0.],
       [ 2.,  6.,  5., -8.,  1.,  0.,  1.,  0.,  0.],
       [ 3.,  9.,  5., -3., -2.,  0.,  0.,  1.,  0.],
       [ 4., 12.,  5.,  2., -5.,  0.,  0.,  0.,  1.]])

In [9]:
# _, pivot_columns = Mextended.rref() # lib
_, pivot_columns = RREF(Mextended)
print(pivot_columns)
pivot_columns = list(map(lambda x: x[1], pivot_columns))
pivot_columns

[[0, 0], [1, 2], [2, 3], [3, 6]]


[0, 2, 3, 6]

In [10]:
base = Mextended[:, pivot_columns]
base

array([[ 1.,  3., -7.,  0.],
       [ 2.,  5., -8.,  1.],
       [ 3.,  5., -3.,  0.],
       [ 4.,  5.,  2.,  0.]])

In [11]:
base = np.array(base).astype(np.float64) # convert to numpy

In [12]:
result = gramSchimidt(base)
print(result)

[[ 1.82574186e-01  5.21749195e-01 -8.33333333e-01  3.91605107e-14]
 [ 3.65148372e-01  6.70820393e-01  5.00000000e-01  4.08248290e-01]
 [ 5.47722558e-01  7.45355992e-02  1.66666667e-01 -8.16496581e-01]
 [ 7.30296743e-01 -5.21749195e-01 -1.66666667e-01  4.08248290e-01]]


In [13]:
print(result @ result.T)

[[ 1.00000000e+00  1.62092562e-14 -2.82197105e-14  2.04018901e-14]
 [ 1.62092562e-14  1.00000000e+00 -6.02268057e-15  4.56490391e-14]
 [-2.82197105e-14 -6.02268057e-15  1.00000000e+00 -4.46397579e-14]
 [ 2.04018901e-14  4.56490391e-14 -4.46397579e-14  1.00000000e+00]]
